/**
 * 国家代码 → 语言映射（代理检测结果本地化；BrowserEditor / BrowserOpenModal 共用）
 */
export const countryLang = {
  CN: 'zh-CN',
  TW: 'zh-TW',
  HK: 'zh-HK',
  US: 'en-US',
  GB: 'en-GB',
  CA: 'en-CA',
  AU: 'en-AU',
  JP: 'ja-JP',
  KR: 'ko-KR',
  DE: 'de-DE',
  FR: 'fr-FR',
  ES: 'es-ES',
  MX: 'es-MX',
  IT: 'it-IT',
  RU: 'ru-RU',
  BR: 'pt-BR',
  PT: 'pt-PT',
  NL: 'nl-NL',
  SE: 'sv-SE',
  NO: 'nb-NO',
  DK: 'da-DK',
  FI: 'fi-FI',
  PL: 'pl-PL',
  TR: 'tr-TR',
  IN: 'hi-IN',
  SA: 'ar-SA',
  AE: 'ar-AE',
  IL: 'he-IL',
  TH: 'th-TH',
  VN: 'vi-VN',
  ID: 'id-ID'
}
